name: smolvla
model:
  type: smolVLAnet
  name: smolVLAnet
  policy_type: smolvla            # 'smolvla'
  model_path: lerobot/smolvla_base
  obs_dim: 9 # TODO change it to state_dim
  action_dim: 8         # Action dimension
  obs_horizon: 1        # Observation dimension
  pred_horizon: 1
  action_horizon: 1
  image_dim: (3, 256, 256) # Image dimension (b,c,h,w)

trainer:
  lr: 2e-4
  batch_size: 1
  max_epochs: 10
  num_workers: 4
  use_bf16: true
  weight_decay: 0.0
