defaults:
  - algo: pizero
  - data: pizero_dataset

# general overrides
seed: 42
output_dir: ./outputs
n_episodes: 1
max_steps: 500
step_sleep: 0.1

# Policy Config
node_name: Policy

# Write video
write_video: True
video_cfg:
  fps: 20
  obs_key: sensors::top_camera::rgb
  save_steps : 500

# Default channel config file used by PolicyNode. Override via CLI if needed.
channel_schema: /nfs/rlteam2/abhineet/dsagent/agent/ark_framework/ark/configs/franka_panda.yaml
global_config: ark_ml/arkml/examples/franka_pick_place/franka_config/global_config.yaml
