defaults:
  - algo: pizero
  - data: pizero_dataset

# general overrides
seed: 42
output_dir: ./outputs
n_episodes: 1
max_steps: 500
step_sleep: 0.1

# Policy Config
node_name: Policy

# Default channel config file used by PolicyNode. Override via CLI if needed.
channel_schema: ark_framework/ark/configs/franka_panda.yaml
global_config: ark_ml/arkml/examples/franka_pick_place/franka_config/global_config.yaml
